theme: # NONE - DEFAULT IS

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - .idea/
  - .git*
  - .editorconfig
  - _config
  - Gemfile
  - Gemfile.lock
  - README.md
